allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - seyfert
  - '@eslint/plugin-kit@0.7.2'
  - eslint@10.4.1 || 10.7.0 || 10.8.0
  - prettier@3.9.4
  - vite@8.1.2
  - '@eslint/eslintrc@3.3.6'
  - discord.js@14.26.5
  - discord-api-types@0.38.51

packages: []
